# Generated by Django 4.1.3 on 2023-01-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_movie_dlink_movie_mlink_movie_tlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tLink',
            field=models.URLField(max_length=1200),
        ),
    ]
