# Generated by Django 4.1.5 on 2023-02-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_movie_cast_alter_movie_tlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='urls',
            field=models.CharField(max_length=300),
        ),
    ]
