# Generated by Django 4.2.2 on 2026-05-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_movie_embedlink"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="cast",
        ),
    ]
