# Generated by Django 4.2.2 on 2026-06-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_image_remove_movie_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='download_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='movie',
            name='file_size',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='movie',
            name='quality',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='movie',
            name='source',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
