# Generated by Django 4.2.2 on 2026-06-02 11:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_movie_created_at_movie_download_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='backdrop',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='MovieProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=120)),
                ('provider_logo', models.TextField(blank=True, max_length=500)),
                ('watch_url', models.TextField(max_length=1000)),
                ('is_free', models.BooleanField(default=False)),
                ('country', models.CharField(default='US', max_length=8)),
                ('last_checked', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(blank=True, max_length=40)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='home.movie')),
            ],
            options={
                'ordering': ('-is_free', 'provider_name'),
                'unique_together': {('movie', 'provider_name', 'country', 'watch_url')},
            },
        ),
    ]
